[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
cache_path = "cache_forge"
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

# Compilation
optimizer = true
optimizer_runs = 200
via_ir = false

# Testing
verbosity = 3
ffi = false

# Gas reporting
gas_reports = ["KaraGovernor", "KaraExecutor", "KaraTreasury", "KaraSafety"]

# Fuzzing
[fuzz]
runs = 256
max_test_rejects = 65536

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
